# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mygrpc.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'mygrpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmygrpc.proto\x12\tMyPackage\"*\n\x07Request\x12\r\n\x05route\x18\x01 \x01(\t\x12\x10\n\x08jsondata\x18\x02 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t2D\n\rReqResService\x12\x33\n\x08SaveJson\x12\x12.MyPackage.Request\x1a\x13.MyPackage.ResponseB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mygrpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_REQUEST']._serialized_start=27
  _globals['_REQUEST']._serialized_end=69
  _globals['_RESPONSE']._serialized_start=71
  _globals['_RESPONSE']._serialized_end=97
  _globals['_REQRESSERVICE']._serialized_start=99
  _globals['_REQRESSERVICE']._serialized_end=167
# @@protoc_insertion_point(module_scope)
